# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STRServiceExample' do
  use_frameworks!

pod 'STRService',:path => '../'
pod 'ObjectMapper', '~> 3.4.2'

pod 'netfox', :configurations => ['Debug']

  target 'STRServiceExampleTests' do
    inherit! :search_paths
    
  end

end
