# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'STRService' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for STRService
pod 'Alamofire', '4.8.0'
pod 'ObjectMapper','3.4.2'
pod 'AlamofireObjectMapper','5.2'
pod "PromiseKit", "~> 6.8"

  target 'STRServiceTests' do
    inherit! :complete
    # Pods for testing
  end
  
  target 'STRServiceHost' do
    inherit! :complete
    # Pods for testing
  end

end
